/**
 * Apply fixes to files
 */

import { promises as fs } from 'node:fs';
import { simpleGit } from 'simple-git';
import type { Fix } from '../types/review.js';
import { getCurrentFileContent } from '../analyzer/diff.js';

const git = simpleGit();

export class FixApplier {
  /**
   * Apply a list of fixes to their respective files
   */
  async applyFixes(fixes: Fix[]): Promise<ApplyResult> {
    const result: ApplyResult = {
      applied: 0,
      failed: 0,
      files: [],
    };

    // Group fixes by file
    const fixesByFile = this.groupByFile(fixes);

    for (const [filePath, fileFixes] of fixesByFile.entries()) {
      try {
        await this.applyFileFixesAsync(filePath, fileFixes);
        result.applied += fileFixes.length;
        result.files.push(filePath);
      } catch (error) {
        console.error(`Failed to apply fixes to ${filePath}:`, error);
        result.failed += fileFixes.length;
      }
    }

    return result;
  }

  /**
   * Apply fixes to a single file
   */
  private async applyFileFixesAsync(filePath: string, fixes: Fix[]): Promise<void> {
    // Read current file content
    let content = await getCurrentFileContent(filePath);
    const lines = content.split('\n');

    // Sort fixes from highest to lowest line number
    // This allows us to apply fixes from bottom to top without affecting line numbers
    const sortedFixes = [...fixes].sort((a, b) => b.lineStart - a.lineStart);

    // Apply each fix
    for (const fix of sortedFixes) {
      const startIdx = fix.lineStart - 1;
      const endIdx = fix.lineEnd - 1;

      if (startIdx < 0 || startIdx >= lines.length) {
        console.warn(
          `Fix for ${filePath} has invalid line range: ${fix.lineStart}-${fix.lineEnd}`
        );
        continue;
      }

      // Replace the affected lines with the fixed code
      const fixedLines = fix.fixedCode.split('\n');
      lines.splice(startIdx, endIdx - startIdx + 1, ...fixedLines);
    }

    // Write the fixed content back to file
    const newContent = lines.join('\n');
    await fs.writeFile(filePath, newContent, 'utf-8');
  }

  /**
   * Commit applied fixes to git
   */
  async commitFixes(
    files: string[],
    fixCount: number
  ): Promise<string> {
    if (files.length === 0) {
      throw new Error('No files to commit');
    }

    // Stage the files
    await git.add(files);

    // Create commit message
    const message = this.buildCommitMessage(fixCount, files.length);

    // Commit the changes
    await git.commit(message);

    // Get the commit SHA
    const log = await git.log({ maxCount: 1 });
    return log.latest?.hash || 'unknown';
  }

  /**
   * Build a commit message for auto-fixes
   */
  private buildCommitMessage(fixCount: number, fileCount: number): string {
    const fileWord = fileCount === 1 ? 'file' : 'files';
    const fixWord = fixCount === 1 ? 'fix' : 'fixes';

    return `chore: auto-fix ${fixCount} ${fixWord} in ${fileCount} ${fileWord}

Applied automatic fixes for:
- Code style issues
- Documentation improvements

Generated by Ollama Code Review Bot
🤖 Co-Authored-By: Ollama Bot <noreply@ollama.ai>`;
  }

  /**
   * Group fixes by file path
   */
  private groupByFile(fixes: Fix[]): Map<string, Fix[]> {
    const groups = new Map<string, Fix[]>();

    for (const fix of fixes) {
      if (!groups.has(fix.file)) {
        groups.set(fix.file, []);
      }
      groups.get(fix.file)!.push(fix);
    }

    return groups;
  }

  /**
   * Validate that fixes can be applied safely
   */
  async validateBeforeApply(fixes: Fix[]): Promise<ValidationResult> {
    const result: ValidationResult = {
      valid: true,
      errors: [],
    };

    for (const fix of fixes) {
      // Check if file exists
      try {
        await fs.access(fix.file);
      } catch {
        result.valid = false;
        result.errors.push(`File not found: ${fix.file}`);
        continue;
      }

      // Check if fix has valid content
      if (!fix.fixedCode || fix.fixedCode.trim() === '') {
        result.valid = false;
        result.errors.push(`Empty fix for ${fix.file}`);
      }

      // Check if line range is valid
      const content = await getCurrentFileContent(fix.file);
      const lineCount = content.split('\n').length;

      if (fix.lineStart < 1 || fix.lineStart > lineCount) {
        result.valid = false;
        result.errors.push(
          `Invalid line range for ${fix.file}: ${fix.lineStart}-${fix.lineEnd}`
        );
      }
    }

    return result;
  }

  /**
   * Create a backup of files before applying fixes
   */
  async createBackup(files: string[]): Promise<Map<string, string>> {
    const backups = new Map<string, string>();

    for (const file of files) {
      try {
        const content = await getCurrentFileContent(file);
        backups.set(file, content);
      } catch (error) {
        console.error(`Failed to backup ${file}:`, error);
      }
    }

    return backups;
  }

  /**
   * Restore files from backup
   */
  async restoreBackup(backups: Map<string, string>): Promise<void> {
    for (const [file, content] of backups.entries()) {
      try {
        await fs.writeFile(file, content, 'utf-8');
      } catch (error) {
        console.error(`Failed to restore ${file}:`, error);
      }
    }
  }
}

export interface ApplyResult {
  applied: number;
  failed: number;
  files: string[];
}

export interface ValidationResult {
  valid: boolean;
  errors: string[];
}
